### ISSUE TITLE
Verify Yomichan is using MeCab?

### ISSUE THREAD

**Issue by lukeburns** [siikamiika/yomichan-mecab-installer#2]
I've installed MeCab, and the yomichan-mecab installer executed successfully, but I'm not sure how to check if Yomichan is using MeCab to parse. How do I verify everything's working properly?

<img width="655" alt="Screen Shot 2021-01-05 at 3 59 04 PM" src="https://user-images.githubusercontent.com/189068/103712534-f0ce9780-4f6e-11eb-9085-0f30311bd983.png">

**Comment by toasted-nutbread** [comment]
Created a task for this on the Yomichan repo.
https://github.com/FooSoft/yomichan/issues/1356

**Comment by siikamiika** [comment]
Thanks @toasted-nutbread !
